[package]
name = "eventemitter"
version = "0.1.0"
authors = ["heapwolf <paolo@async.ly>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
